import { Client } from "pg";

/** Same host/port/user/password/query-string as `baseUrl`, but pointed at a different database name - used to create/drop drill databases and to connect to the `postgres` maintenance database (you cannot CREATE/DROP DATABASE while connected to that same database). */
export function buildDatabaseUrl(baseUrl: string, databaseName: string): string {
  const url = new URL(baseUrl);
  url.pathname = `/${databaseName}`;
  return url.toString();
}

/** Only ever generated by disaster-recovery-drill.ts with a fixed prefix + timestamp - never derived from user input. */
const SAFE_DB_NAME_PATTERN = /^[a-zA-Z][a-zA-Z0-9_]*$/;

function assertSafeDatabaseName(name: string): void {
  if (!SAFE_DB_NAME_PATTERN.test(name)) {
    throw new Error(`안전하지 않은 데이터베이스 이름입니다: ${name}`);
  }
}

export async function createDatabase(baseUrl: string, databaseName: string): Promise<void> {
  assertSafeDatabaseName(databaseName);
  const maintenanceUrl = buildDatabaseUrl(baseUrl, "postgres");
  const client = new Client({ connectionString: maintenanceUrl });
  await client.connect();
  try {
    // Database names cannot be parameterized as a bind value in DDL -
    // assertSafeDatabaseName() above is what makes this identifier safe to
    // interpolate (fixed alphanumeric/underscore pattern only).
    await client.query(`CREATE DATABASE "${databaseName}"`);
  } finally {
    await client.end();
  }
}

export async function dropDatabase(baseUrl: string, databaseName: string): Promise<void> {
  assertSafeDatabaseName(databaseName);
  const maintenanceUrl = buildDatabaseUrl(baseUrl, "postgres");
  const client = new Client({ connectionString: maintenanceUrl });
  await client.connect();
  try {
    await client.query(`DROP DATABASE IF EXISTS "${databaseName}" WITH (FORCE)`);
  } finally {
    await client.end();
  }
}
