/**
 * Storage abstraction so the local filesystem driver can be swapped for
 * AWS S3 / Cloudflare R2 later without touching callers. Callers never talk
 * to the filesystem or an SDK directly - only to this interface.
 */
import type { StoredFile } from "@/domain/shared/storage";

export type { StoredFile } from "@/domain/shared/storage";

export interface PutFileInput {
  /** Random key generated by generateStorageKey(), not a user-supplied path. */
  key: string;
  data: Buffer;
  mimeType: string;
}

export interface StorageDriver {
  put(input: PutFileInput): Promise<StoredFile>;
  getBuffer(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
}

export interface ListKeysPage {
  keys: string[];
  /** Present iff more keys remain - pass back into the next call's `continuationToken`. */
  nextContinuationToken?: string;
}

/**
 * Separate, optional operational/maintenance interface - deliberately NOT
 * folded into StorageDriver, since "list keys" is not something every
 * backend can (or should) support cheaply, and never as a single
 * unbounded array (Phase 10A §12 - a real bucket/directory can hold far
 * more objects than is safe to hold in memory at once). Every
 * implementation - local or S3 - pages through real pagination state
 * (`continuationToken`), so this same interface and the same calling code
 * in find-orphan-files.ts works for both without a size assumption baked
 * into either. See getStorageMaintenanceDriver().
 */
export interface StorageMaintenanceDriver {
  listKeysPage(continuationToken?: string, maxKeys?: number): Promise<ListKeysPage>;
}
