export const AUDIT_ACTIONS = {
  ORGANIZATION_CREATED: "ORGANIZATION_CREATED",
  CONTRACT_CREATED: "CONTRACT_CREATED",
  CONTRACT_UPDATED: "CONTRACT_UPDATED",
  CONTRACT_DELETED: "CONTRACT_DELETED",
  COUNTERPARTY_CREATED: "COUNTERPARTY_CREATED",
  COUNTERPARTY_UPDATED: "COUNTERPARTY_UPDATED",
  COUNTERPARTY_DELETED: "COUNTERPARTY_DELETED",
  FILE_UPLOADED: "FILE_UPLOADED",
  FILE_DOWNLOADED: "FILE_DOWNLOADED",
  FILE_DELETED: "FILE_DELETED",
  MEMBER_INVITED: "MEMBER_INVITED",
  MEMBER_INVITATION_REVOKED: "MEMBER_INVITATION_REVOKED",
  MEMBER_INVITATION_RESENT: "MEMBER_INVITATION_RESENT",
  MEMBER_INVITATION_ACCEPTED: "MEMBER_INVITATION_ACCEPTED",
  MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  EXTRACTION_JOB_CREATED: "EXTRACTION_JOB_CREATED",
  EXTRACTION_JOB_STARTED: "EXTRACTION_JOB_STARTED",
  EXTRACTION_JOB_FAILED: "EXTRACTION_JOB_FAILED",
  EXTRACTION_REVIEW_REQUIRED: "EXTRACTION_REVIEW_REQUIRED",
  EXTRACTION_SUGGESTION_REVIEWED: "EXTRACTION_SUGGESTION_REVIEWED",
  EXTRACTION_APPLIED: "EXTRACTION_APPLIED",
  EXTRACTION_RETRY_REQUESTED: "EXTRACTION_RETRY_REQUESTED",
  CLAUSE_SEGMENTATION_JOB_CREATED: "CLAUSE_SEGMENTATION_JOB_CREATED",
  CLAUSE_SEGMENTATION_STARTED: "CLAUSE_SEGMENTATION_STARTED",
  CLAUSE_SEGMENTATION_FAILED: "CLAUSE_SEGMENTATION_FAILED",
  CLAUSE_SEGMENTATION_REVIEW_REQUIRED: "CLAUSE_SEGMENTATION_REVIEW_REQUIRED",
  CLAUSE_SEGMENTATION_RETRY_REQUESTED: "CLAUSE_SEGMENTATION_RETRY_REQUESTED",
  CLAUSE_CLASSIFICATION_REVIEWED: "CLAUSE_CLASSIFICATION_REVIEWED",
  CLAUSE_STANDARD_CREATED: "CLAUSE_STANDARD_CREATED",
  CLAUSE_STANDARD_UPDATED: "CLAUSE_STANDARD_UPDATED",
  CLAUSE_STANDARD_DELETED: "CLAUSE_STANDARD_DELETED",
  CLAUSE_REVIEW_SIGNALS_GENERATED: "CLAUSE_REVIEW_SIGNALS_GENERATED",
  CLAUSE_REVIEW_SIGNAL_UPDATED: "CLAUSE_REVIEW_SIGNAL_UPDATED",
  CLAUSE_COMPARISON_VIEWED: "CLAUSE_COMPARISON_VIEWED",
  ANALYTICS_CSV_EXPORTED: "ANALYTICS_CSV_EXPORTED",
  // Phase 9 - retention/purge. Metadata never includes contract/clause
  // text or file storageKeys - entity id only (§5's "민감 데이터 로그 금지").
  CONTRACT_PURGED: "CONTRACT_PURGED",
  CONTRACT_PURGE_FAILED: "CONTRACT_PURGE_FAILED",
  // Phase 9 - account security. Metadata never includes the token
  // (plaintext or hash), password, or password hash.
  EMAIL_VERIFICATION_REQUESTED: "EMAIL_VERIFICATION_REQUESTED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  // Phase 10C - stale token mail recovery (scripts/recover-stale-token-deliveries.ts).
  // Metadata never includes the token (plaintext or hash), only the stale
  // MailDelivery id and which entity was rotated.
  STALE_TOKEN_MAIL_INVITATION_RECOVERED: "STALE_TOKEN_MAIL_INVITATION_RECOVERED",
  STALE_TOKEN_MAIL_VERIFICATION_RECOVERED: "STALE_TOKEN_MAIL_VERIFICATION_RECOVERED",
  STALE_TOKEN_MAIL_PASSWORD_RESET_FLAGGED: "STALE_TOKEN_MAIL_PASSWORD_RESET_FLAGGED",
  // Phase 12 - AI Contract Intelligence Platform (§Similar Clause, §AI Review).
  SIMILAR_CLAUSES_VIEWED: "SIMILAR_CLAUSES_VIEWED",
  AI_CLAUSE_REVIEW_GENERATED: "AI_CLAUSE_REVIEW_GENERATED",
  // §Phase 15.1 - minimal Closed Beta funnel instrumentation (§Part 2/3 of
  // the Phase 15 audit's telemetry mapping). Every event below reuses this
  // existing AuditLog backbone - no new table, no event/prompt/answer
  // content in metadata, ever.
  USER_LOGIN: "USER_LOGIN",
  CONTRACT_VIEWED: "CONTRACT_VIEWED",
  AI_QA_OPENED: "AI_QA_OPENED",
  AI_CITATION_INSPECTED: "AI_CITATION_INSPECTED",
  FEEDBACK_SUBMITTED: "FEEDBACK_SUBMITTED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
