/**
 * The one storage key shape every driver accepts - only ever generated by
 * generateStorageKey() (see server/storage/key-generator.ts):
 * `<organizationId>/<uuid>.<ext>`. Shared by every StorageDriver
 * implementation (local, S3-compatible, ...) so a key that was valid for
 * one driver is always structurally valid for another - required for
 * mixed-storage support (Phase 10A §35), where the same `storageKey`
 * column has to make sense regardless of which provider a given
 * ContractFile row actually lives on.
 */
export const STORAGE_KEY_PATTERN = /^[a-zA-Z0-9_-]+\/[a-zA-Z0-9-]+\.[a-z0-9]+$/;

export function isValidStorageKey(key: string): boolean {
  return STORAGE_KEY_PATTERN.test(key);
}
